if(EXISTS "/home/dries/Documents/Thesis/code/tglib/tglib_cpp/build-release/test/custom-main-tests_tests-b12d07c.cmake")
  include("/home/dries/Documents/Thesis/code/tglib/tglib_cpp/build-release/test/custom-main-tests_tests-b12d07c.cmake")
else()
  add_test(custom-main-tests_NOT_BUILT-b12d07c custom-main-tests_NOT_BUILT-b12d07c)
endif()
