add_test( [==[edge_burstiness non-bursty]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[edge_burstiness non-bursty]==]  )
set_tests_properties( [==[edge_burstiness non-bursty]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[edge_burstiness random]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[edge_burstiness random]==]  )
set_tests_properties( [==[edge_burstiness random]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[burstiness example]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[burstiness example]==]  )
set_tests_properties( [==[burstiness example]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[edge_burstiness bursty]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[edge_burstiness bursty]==]  )
set_tests_properties( [==[edge_burstiness bursty]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[node_burstiness non-bursty]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[node_burstiness non-bursty]==]  )
set_tests_properties( [==[node_burstiness non-bursty]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[node_burstiness bursty]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[node_burstiness bursty]==]  )
set_tests_properties( [==[node_burstiness bursty]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[reachability chain]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[reachability chain]==]  )
set_tests_properties( [==[reachability chain]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[duration example]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[duration example]==]  )
set_tests_properties( [==[duration example]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[ea example]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[ea example]==]  )
set_tests_properties( [==[ea example]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[short example]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[short example]==]  )
set_tests_properties( [==[short example]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[dur infectious]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[dur infectious]==]  )
set_tests_properties( [==[dur infectious]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[example ua ea2]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[example ua ea2]==]  )
set_tests_properties( [==[example ua ea2]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[short example hops]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[short example hops]==]  )
set_tests_properties( [==[short example hops]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[short example mintrans]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[short example mintrans]==]  )
set_tests_properties( [==[short example mintrans]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[temporal diameter]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[temporal diameter]==]  )
set_tests_properties( [==[temporal diameter]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[ea path]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[ea path]==]  )
set_tests_properties( [==[ea path]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[fastest path]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[fastest path]==]  )
set_tests_properties( [==[fastest path]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[shorstest path]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[shorstest path]==]  )
set_tests_properties( [==[shorstest path]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[minhop path]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[minhop path]==]  )
set_tests_properties( [==[minhop path]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[value chain node 0]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[value chain node 0]==]  )
set_tests_properties( [==[value chain node 0]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[value chain topk]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[value chain topk]==]  )
set_tests_properties( [==[value chain topk]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[closeness example]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[closeness example]==]  )
set_tests_properties( [==[closeness example]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[rnd tg compare with exact]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[rnd tg compare with exact]==]  )
set_tests_properties( [==[rnd tg compare with exact]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[edge betweenness]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[edge betweenness]==]  )
set_tests_properties( [==[edge betweenness]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[no topological overlap example]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[no topological overlap example]==]  )
set_tests_properties( [==[no topological overlap example]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[full topological overlap example]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[full topological overlap example]==]  )
set_tests_properties( [==[full topological overlap example]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[temporal clustering coefficient chain]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[temporal clustering coefficient chain]==]  )
set_tests_properties( [==[temporal clustering coefficient chain]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[temporal clustering coefficient K_5]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[temporal clustering coefficient K_5]==]  )
set_tests_properties( [==[temporal clustering coefficient K_5]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[example topk random]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[example topk random]==]  )
set_tests_properties( [==[example topk random]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[example topk shortest]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[example topk shortest]==]  )
set_tests_properties( [==[example topk shortest]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[temporal efficiency chain]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[temporal efficiency chain]==]  )
set_tests_properties( [==[temporal efficiency chain]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[temporal kcore]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[temporal kcore]==]  )
set_tests_properties( [==[temporal kcore]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[temporal edge compare]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[temporal edge compare]==]  )
set_tests_properties( [==[temporal edge compare]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[temporal edge set]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[temporal edge set]==]  )
set_tests_properties( [==[temporal edge set]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[temporal edge sort]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[temporal edge sort]==]  )
set_tests_properties( [==[temporal edge sort]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( copy /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests copy  )
set_tests_properties( copy PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[TRS example]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[TRS example]==]  )
set_tests_properties( [==[TRS example]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[no normalization]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[no normalization]==]  )
set_tests_properties( [==[no normalization]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( normalization /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests normalization  )
set_tests_properties( normalization PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[normalization, keep loops]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[normalization\, keep loops]==]  )
set_tests_properties( [==[normalization, keep loops]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[normalization, non sorted rnd graph]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[normalization\, non sorted rnd graph]==]  )
set_tests_properties( [==[normalization, non sorted rnd graph]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[scale example 10]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[scale example 10]==]  )
set_tests_properties( [==[scale example 10]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[unit transition times]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[unit transition times]==]  )
set_tests_properties( [==[unit transition times]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[reverse tg test]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[reverse tg test]==]  )
set_tests_properties( [==[reverse tg test]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[topkresult top50 out of 1000]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[topkresult top50 out of 1000]==]  )
set_tests_properties( [==[topkresult top50 out of 1000]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
add_test( [==[load example]==] /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test/custom-main-tests [==[load example]==]  )
set_tests_properties( [==[load example]==] PROPERTIES WORKING_DIRECTORY /home/dries/Documents/Thesis/code/tglib-main/tglib_cpp/build-release/test)
set( custom-main-tests_TESTS [==[edge_burstiness non-bursty]==] [==[edge_burstiness random]==] [==[burstiness example]==] [==[edge_burstiness bursty]==] [==[node_burstiness non-bursty]==] [==[node_burstiness bursty]==] [==[reachability chain]==] [==[duration example]==] [==[ea example]==] [==[short example]==] [==[dur infectious]==] [==[example ua ea2]==] [==[short example hops]==] [==[short example mintrans]==] [==[temporal diameter]==] [==[ea path]==] [==[fastest path]==] [==[shorstest path]==] [==[minhop path]==] [==[value chain node 0]==] [==[value chain topk]==] [==[closeness example]==] [==[rnd tg compare with exact]==] [==[edge betweenness]==] [==[no topological overlap example]==] [==[full topological overlap example]==] [==[temporal clustering coefficient chain]==] [==[temporal clustering coefficient K_5]==] [==[example topk random]==] [==[example topk shortest]==] [==[temporal efficiency chain]==] [==[temporal kcore]==] [==[temporal edge compare]==] [==[temporal edge set]==] [==[temporal edge sort]==] copy [==[TRS example]==] [==[no normalization]==] normalization [==[normalization, keep loops]==] [==[normalization, non sorted rnd graph]==] [==[scale example 10]==] [==[unit transition times]==] [==[reverse tg test]==] [==[topkresult top50 out of 1000]==] [==[load example]==])
